org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Suppress Groovy space-assignment deprecation warnings from third-party plugins
org.gradle.warning.mode=none

# Suppress configuration cache problems from third-party plugins
android.suppressGroovyDeprecatedSpaceAssignment=true
