// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs1Indsfl5ZihLKYzwFzp97or9XjQtmIw',
    appId: '1:53130391717:web:bf8625b9761ca8eb01dd4c',
    messagingSenderId: '53130391717',
    projectId: 'music-app-123-a5022',
    authDomain: 'music-app-123-a5022.firebaseapp.com',
    storageBucket: 'music-app-123-a5022.firebasestorage.app',
    measurementId: 'G-6902115TYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7HhGWr8MU7iV5l9_r62f_I3-ev0Rc4H8',
    appId: '1:53130391717:android:8cd6ded23aeb877d01dd4c',
    messagingSenderId: '53130391717',
    projectId: 'music-app-123-a5022',
    storageBucket: 'music-app-123-a5022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3MbeEXqQK9yTtVlGMIfFCXVJjDIkMv0',
    appId: '1:53130391717:ios:5fb687f76b09a3da01dd4c',
    messagingSenderId: '53130391717',
    projectId: 'music-app-123-a5022',
    storageBucket: 'music-app-123-a5022.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO3MbeEXqQK9yTtVlGMIfFCXVJjDIkMv0',
    appId: '1:53130391717:ios:5fb687f76b09a3da01dd4c',
    messagingSenderId: '53130391717',
    projectId: 'music-app-123-a5022',
    storageBucket: 'music-app-123-a5022.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs1Indsfl5ZihLKYzwFzp97or9XjQtmIw',
    appId: '1:53130391717:web:2b3aa7d6d2a9f53c01dd4c',
    messagingSenderId: '53130391717',
    projectId: 'music-app-123-a5022',
    authDomain: 'music-app-123-a5022.firebaseapp.com',
    storageBucket: 'music-app-123-a5022.firebasestorage.app',
    measurementId: 'G-FB7Q1Z84L5',
  );
}
